export const OK = "Ok"
export const CREATED = "Created"
export const NOT_FOUND = "Not Found"
export const UNPROCESSABLE_CONTENT = "Unprocessable Content"
export const INTERNAL_SERVER_ERROR = "Internal Server Error"
